name: Build my gitbook and deploy to gh-pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: install nodejs
        uses: actions/setup-node@v1

      - name: configue honkit
        run: |
          npm install
      - name: generate _book folder
        run: |
          npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: ./_book
